GMAIL_USERNAME: 'denis.dikiy@gmail.com'
GMAIL_PASSWORD: 'zrcplhhgskjqefbe'
FACEBOOK_APP_ID: '2749460155376289'
FACEBOOK_SECRET: '5b96afe3508ec0fea66dc56dc9f6ab06'
GOOGLE_CLIENT_ID: '500357250676-7tnu83kg0tirkahleutvtoo6e2unntbp.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: 'H99SKSfWVVKxsxVJAMBzpppj'